# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-30 00:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Academy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(verbose_name='\u5b66\u9662ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u5b66\u9662\u540d\u79f0')),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(unique=True, verbose_name='\u7ba1\u7406\u5458ID')),
                ('name', models.CharField(max_length=10, verbose_name='\u7ba1\u7406\u5458\u540d\u79f0')),
                ('image', models.ImageField(blank=True, default='/avatar/default.jpg', upload_to='/avatar', verbose_name='\u5934\u50cf')),
                ('cellphone', models.CharField(max_length=15, verbose_name='\u624b\u673a\u53f7')),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Academy', verbose_name='\u6240\u5728\u5b66\u9662')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(verbose_name='\u7cfbID')),
                ('name', models.CharField(max_length=100, verbose_name='\u7cfb\u540d\u79f0')),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(unique=True, verbose_name='\u6559\u5e08ID')),
                ('name', models.CharField(max_length=10, verbose_name='\u6559\u5e08\u540d')),
                ('image', models.ImageField(blank=True, default='/avatar/default.jpg', upload_to='/avatar', verbose_name='\u5934\u50cf')),
                ('cellphone', models.CharField(max_length=15, verbose_name='\u624b\u673a\u53f7')),
            ],
        ),
        migrations.CreateModel(
            name='PaperDemo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(choices=[(0, '\u5f00\u9898\u62a5\u544a'), (1, '\u5916\u6587\u7ffb\u8bd1'), (2, '\u8bba\u6587\u6b63\u7a3f')], verbose_name='\u6587\u6863\u8303\u4f8b\u7c7b\u578b')),
                ('status', models.SmallIntegerField(choices=[(0, '\u672a\u4e0a\u4f20'), (1, '\u5df2\u4e0a\u4f20')], verbose_name='\u6587\u6863\u8303\u4f8b\u72b6\u6001')),
                ('title', models.CharField(max_length=100, verbose_name='\u6587\u6863\u8303\u4f8b\u6807\u9898')),
                ('file', models.FileField(blank=True, upload_to='/paper_demo', verbose_name='\u6587\u6863\u8303\u4f8b\u94fe\u63a5')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='\u4e0a\u4f20\u65f6\u95f4')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
            ],
        ),
        migrations.CreateModel(
            name='PaperDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(choices=[(0, '\u5f00\u9898\u62a5\u544a'), (1, '\u5916\u6587\u7ffb\u8bd1'), (2, '\u8bba\u6587\u6b63\u7a3f')], verbose_name='\u6587\u6863\u7c7b\u578b')),
                ('status', models.SmallIntegerField(choices=[(0, '\u672a\u4e0a\u4f20'), (1, '\u5df2\u4e0a\u4f20')], verbose_name='\u6587\u6863\u72b6\u6001')),
                ('file', models.FileField(upload_to='/paper', verbose_name='\u6587\u6863')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='\u4e0a\u4ea4\u65f6\u95f4')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
            ],
        ),
        migrations.CreateModel(
            name='PaperSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='\u9009\u4e2d\u65f6\u95f4')),
                ('modify_time', models.DateField(auto_now=True, verbose_name='\u6539\u52a8\u65f6\u95f4')),
            ],
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(unique=True, verbose_name='\u4e13\u4e1aID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='\u4e13\u4e1a\u540d\u79f0')),
                ('short_name', models.CharField(max_length=20, verbose_name='\u4e13\u4e1a\u7b80\u79f0')),
                ('type', models.SmallIntegerField(choices=[(0, '\u54f2\u5b66'), (1, '\u7ecf\u6d4e\u5b66'), (2, '\u6cd5\u5b66'), (3, '\u6559\u80b2\u5b66'), (4, '\u6587\u5b66'), (5, '\u5386\u53f2\u5b66'), (6, '\u7406\u5b66'), (7, '\u5de5\u5b66'), (8, '\u519c\u5b66'), (9, '\u533b\u5b66'), (10, '\u519b\u4e8b\u5b66'), (11, '\u7ba1\u7406\u5b66')], verbose_name='\u4e13\u4e1a\u5206\u7c7b')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(unique=True, verbose_name='\u5b66\u751fID')),
                ('name', models.CharField(max_length=100, verbose_name='\u5b66\u751f\u540d')),
                ('image', models.ImageField(blank=True, default='/avatar/default.jpg', upload_to='/avatar', verbose_name='\u5934\u50cf')),
                ('cellphone', models.CharField(max_length=15, verbose_name='\u624b\u673a\u53f7')),
                ('Speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Speciality', verbose_name='\u4e13\u4e1a')),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Academy', verbose_name='\u6240\u5728\u5b66\u9662')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Department', verbose_name='\u6240\u5728\u7cfb')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Thesis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(unique=True, verbose_name='\u8bba\u6587ID')),
                ('title', models.CharField(max_length=200, verbose_name='\u8bba\u6587\u9898\u76ee')),
                ('content', models.TextField(verbose_name='\u8bba\u6587\u8981\u6c42')),
                ('status', models.SmallIntegerField(choices=[(0, '\u672a\u53d1\u5e03'), (1, '\u5df2\u53d1\u5e03'), (2, '\u672a\u9009\u4e2d'), (3, '\u5df2\u9009\u4e2d')], default=0, verbose_name='\u8bba\u6587\u72b6\u6001')),
                ('start_time', models.DateField(verbose_name='\u9009\u9898\u5f00\u59cb\u65f6\u95f4')),
                ('end_time', models.DateField(verbose_name='\u9009\u9898\u7ed3\u675f\u65f6\u95f4')),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('modify_time', models.DateField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Academy', verbose_name='\u6240\u5c5e\u5b66\u9662')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Instructor', verbose_name='\u8f85\u5bfc\u8001\u5e08')),
            ],
        ),
        migrations.AddField(
            model_name='papersection',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Student', verbose_name='\u5b66\u751f'),
        ),
        migrations.AddField(
            model_name='papersection',
            name='thesis',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Thesis', verbose_name='\u8bba\u6587\u9009\u9898'),
        ),
        migrations.AddField(
            model_name='paperdocuments',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Student', verbose_name='\u5b66\u751f'),
        ),
        migrations.AddField(
            model_name='paperdocuments',
            name='thesis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Thesis', verbose_name='\u8bba\u6587\u9009\u9898'),
        ),
        migrations.AddField(
            model_name='paperdemo',
            name='thesis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Thesis', verbose_name='\u8bba\u6587\u9009\u9898'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='Speciality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Speciality', verbose_name='\u4e13\u4e1a'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='academy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Academy', verbose_name='\u6240\u5728\u5b66\u9662'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Department', verbose_name='\u6240\u5728\u7cfb'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='speciality',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Speciality', verbose_name='\u4e13\u4e1a'),
        ),
        migrations.AddField(
            model_name='admin',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Department', verbose_name='\u6240\u5728\u7cfb'),
        ),
        migrations.AddField(
            model_name='admin',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='academy',
            name='department',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Department', verbose_name='\u7cfb'),
        ),
        migrations.AlterUniqueTogether(
            name='paperdocuments',
            unique_together=set([('thesis', 'student', 'type')]),
        ),
        migrations.AlterUniqueTogether(
            name='paperdemo',
            unique_together=set([('thesis', 'type')]),
        ),
    ]
