# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-29 11:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_superadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='department',
        ),
    ]
