# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-29 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_admin_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerityCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='\u90ae\u7bb1')),
                ('code', models.CharField(max_length=20, null=True, verbose_name='\u9a8c\u8bc1\u7801')),
                ('code_type', models.SmallIntegerField(choices=[(1, '\u6fc0\u6d3b\u8d26\u6237'), (2, '\u5fd8\u8bb0\u5bc6\u7801')], verbose_name='\u9a8c\u8bc1\u7801\u7c7b\u578b')),
                ('is_used', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5df2\u7ecf\u4f7f\u7528')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('expire_time', models.DateTimeField(verbose_name='\u8fc7\u671f\u65f6\u95f4')),
            ],
        ),
    ]
