# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-30 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_veritycode_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thesis',
            name='index',
        ),
        migrations.AlterField(
            model_name='thesis',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='\u8bba\u6587\u9898\u76ee'),
        ),
    ]
