# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-30 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20160430_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='cellphone',
            field=models.CharField(default='', max_length=15, verbose_name='\u624b\u673a\u53f7'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='cellphone',
            field=models.CharField(default='', max_length=15, verbose_name='\u624b\u673a\u53f7'),
        ),
        migrations.AlterField(
            model_name='student',
            name='cellphone',
            field=models.CharField(default='', max_length=15, verbose_name='\u624b\u673a\u53f7'),
        ),
        migrations.AlterField(
            model_name='superadmin',
            name='cellphone',
            field=models.CharField(default='', max_length=15, verbose_name='\u624b\u673a\u53f7'),
        ),
    ]
