# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-02 06:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20160430_0159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='speciality',
        ),
        migrations.RenameField(
            model_name='instructor',
            old_name='Speciality',
            new_name='speciality',
        ),
        migrations.RemoveField(
            model_name='academy',
            name='department',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='department',
        ),
        migrations.RemoveField(
            model_name='student',
            name='department',
        ),
        migrations.AddField(
            model_name='academy',
            name='speciality',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Speciality', verbose_name='\u4e13\u4e1a'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='academy',
            name='index',
            field=models.IntegerField(unique=True, verbose_name='\u5b66\u9662ID'),
        ),
        migrations.AlterField(
            model_name='veritycode',
            name='code_type',
            field=models.SmallIntegerField(choices=[(1, '\u6fc0\u6d3b\u8d26\u6237'), (2, '\u5fd8\u8bb0\u5bc6\u7801'), (3, '\u91cd\u7f6e\u5bc6\u7801')], verbose_name='\u9a8c\u8bc1\u7801\u7c7b\u578b'),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
