# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-02 06:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20160502_0635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academy',
            name='speciality',
        ),
        migrations.AddField(
            model_name='speciality',
            name='academy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Academy', verbose_name='\u6240\u5c5e\u5b66\u9662'),
            preserve_default=False,
        ),
    ]
