# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-04 09:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20160502_0646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speciality',
            name='type',
        ),
    ]
