# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-09 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_speciality_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veritycode',
            name='code',
            field=models.CharField(max_length=32, null=True, verbose_name='\u9a8c\u8bc1\u7801'),
        ),
    ]
