# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-11 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20160509_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='academy',
            name='short_name',
            field=models.CharField(default='abc', max_length=20, verbose_name='\u5b66\u9662\u7b80\u79f0'),
            preserve_default=False,
        ),
    ]
