# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-12 07:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20160511_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veritycode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
