# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-13 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20160512_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papersection',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u9009\u4e2d\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='papersection',
            name='modify_time',
            field=models.DateTimeField(auto_now=True, verbose_name='\u6539\u52a8\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='modify_time',
            field=models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4'),
        ),
    ]
