# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-13 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20160513_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='end_time',
            field=models.DateTimeField(verbose_name='\u9009\u9898\u7ed3\u675f\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='start_time',
            field=models.DateTimeField(verbose_name='\u9009\u9898\u5f00\u59cb\u65f6\u95f4'),
        ),
    ]
